In [1]:
import pandas as pd
import numpy as np
import ta
import xgboost as xgb
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
import requests
import feedparser
from sklearn.model_selection import GridSearchCV

/Users/redietmebrat/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [2]:

#Fetching of data from serveral sources and merging

oanda_api_key = "b9846701e3d5d9b2d73127d5040aac28-5d86be73abbdec141a31891cb532d340"
oanda_url = "https://api-fxpractice.oanda.com/v3/instruments/EUR_USD/candles?granularity=M30"
headers = {"Authorization": f"Bearer {oanda_api_key}"}
response = requests.get(oanda_url, headers=headers).json()

forex_data = pd.DataFrame(response['candles'])


if 'mid' in forex_data.columns:
    forex_data['open'] = forex_data['mid'].apply(lambda x: float(x['o']))
    forex_data['high'] = forex_data['mid'].apply(lambda x: float(x['h']))
    forex_data['low'] = forex_data['mid'].apply(lambda x: float(x['l']))
    forex_data['close'] = forex_data['mid'].apply(lambda x: float(x['c']))
    forex_data.drop(columns=['mid'], inplace=True)
else:
    print("'mid' column missing from forex_data!")


forex_data['time'] = pd.to_datetime(forex_data['time']).dt.tz_localize(None)


forex_data['date_time'] = forex_data['time'].dt.floor('D')  
forex_data['rounded_time'] = forex_data['time'].dt.floor('h')  

fred_api_key = "5de83463f5e12c01d110a2322a075ecc"
fred_series = {
    "inflation": "CPIAUCSL",
    "gdp": "GDPC1",
    "unemployment": "UNRATE",
    "interest_rate": "DGS10"
}

def get_fred_data(series_id):
    url = f"https://api.stlouisfed.org/fred/series/observations?series_id={series_id}&api_key={fred_api_key}&file_type=json"
    response = requests.get(url).json()

    if 'observations' not in response:
        print(f"Failed to fetch {series_id}")
        return pd.DataFrame()
    
    data = pd.DataFrame(response['observations'])
    data['date'] = pd.to_datetime(data['date'])
    data[series_id] = pd.to_numeric(data['value'], errors='coerce')
    return data[['date', series_id]]


fred_data = pd.DataFrame()
for label, series_id in fred_series.items():
    indicator_df = get_fred_data(series_id)
    if indicator_df.empty:
        continue
    if fred_data.empty:
        fred_data = indicator_df
    else:
        fred_data = fred_data.merge(indicator_df, on='date', how='outer')

fred_data.sort_values('date', inplace=True)
fred_data.ffill(inplace=True) 


forex_data.sort_values('date_time', inplace=True)
merged_data = pd.merge_asof(
    forex_data,
    fred_data,
    left_on='date_time',
    right_on='date',
    direction='backward'
)

feed_url = "https://feeds.bbci.co.uk/news/business/rss.xml"
feed = feedparser.parse(feed_url)

news_df = pd.DataFrame({
    'headline': [entry.title for entry in feed.entries],
    'datetime': pd.to_datetime([entry.published for entry in feed.entries], errors='coerce')
})

keywords = ['interest rate', 'inflation', 'central bank', 'monetary policy']
news_df = news_df[news_df['headline'].str.contains('|'.join(keywords), case=False, na=False)]

news_df['rounded_time'] = news_df['datetime'].dt.floor('h')  
news_grouped = news_df.groupby('rounded_time').agg({'headline': lambda x: ' | '.join(x)}).reset_index()
merged_data = merged_data.merge(news_grouped, on='rounded_time', how='left')


merged_data = merged_data.drop(columns=['date_time','date','rounded_time', 'headline'])

merged_data = merged_data.sort_values(by='time',ascending=True)

In [3]:
merged_data['price_pct_change'] = (merged_data['close'] - merged_data['open']) / merged_data['open'] * 100
merged_data['price_change'] = merged_data['close'] - merged_data['open']
merged_data['deviation_pts'] = merged_data['price_pct_change']  
merged_data['ema_20'] = ta.trend.ema_indicator(merged_data['close'], window=20) 
merged_data['macd'] = ta.trend.macd(merged_data['close'])  
merged_data['macd_signal'] = ta.trend.macd_signal(merged_data['close'])  
merged_data['rsi'] = ta.momentum.rsi(merged_data['close'], window=14)  
merged_data["time"] = pd.to_datetime(merged_data["time"])
merged_data['volatility'] = merged_data['price_change'].rolling(window=10).std()
merged_data['time'] = pd.to_datetime(merged_data['time'])
merged_data['hour'] = merged_data['time'].dt.hour
merged_data['day_of_week'] = merged_data['time'].dt.dayofweek
merged_data['week_of_year'] = merged_data['time'].dt.isocalendar().week
merged_data['is_weekend'] = merged_data['day_of_week'].apply(lambda x: 1 if x >= 5 else 0)

merged_data

,complete,volume,time,open,high,low,close,CPIAUCSL,GDPC1,UNRATE,...,deviation_pts,ema_20,macd,macd_signal,rsi,volatility,hour,day_of_week,week_of_year,is_weekend
0,True,11958,2025-04-08 14:00:00,1.09359,1.09362,1.09016,1.09054,319.615,23542.349,4.2,...,-0.278898,NaN,NaN,NaN,NaN,NaN,14,1,15,0
18,True,13346,2025-04-08 14:30:00,1.09055,1.09156,1.08883,1.09102,319.615,23542.349,4.2,...,0.043098,NaN,NaN,NaN,NaN,NaN,14,1,15,0
17,True,9974,2025-04-08 15:00:00,1.09103,1.09168,1.08959,1.09118,319.615,23542.349,4.2,...,0.013748,NaN,NaN,NaN,NaN,NaN,15,1,15,0
16,True,7763,2025-04-08 15:30:00,1.09119,1.09194,1.09062,1.09118,319.615,23542.349,4.2,...,-0.000916,NaN,NaN,NaN,NaN,NaN,15,1,15,0
15,True,6892,2025-04-08 16:00:00,1.09120,1.09126,1.08986,1.09124,319.615,23542.349,4.2,...,0.003666,NaN,NaN,NaN,NaN,NaN,16,1,15,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
470,True,1654,2025-04-22 21:30:00,1.14086,1.14086,1.13627,1.13631,319.615,23542.349,4.2,...,-0.398822,1.143883,-0.002519,-0.001979,18.048372,0.001575,21,1,17,0
471,True,9131,2025-04-22 22:00:00,1.13630,1.13703,1.13152,1.13176,319.615,23542.349,4.2,...,-0.399542,1.142728,-0.003171,-0.002218,13.491937,0.001837,22,1,17,0
462,True,7603,2025-04-22 22:30:00,1.13178,1.13444,1.13080,1.13378,319.615,23542.349,4.2,...,0.176713,1.141876,-0.003484,-0.002471,22.808990,0.002043,22,1,17,0
477,True,7809,2025-04-22 23:00:00,1.13379,1.13598,1.13298,1.13480,319.615,23542.349,4.2,...,0.089082,1.141202,-0.003609,-0.002698,27.079735,0.002147,23,1,17,0
499,False,1370,2025-04-22 23:30:00,1.13480,1.13518,1.13440,1.13516,319.615,23542.349,4.2,...,0.031724,1.140627,-0.003636,-0.002886,28.581611,0.002185,23,1,17,0

In [4]:
# Define RSI thresholds
rsi_buy_threshold = 45  # RSI below 35 suggests oversold (buy)
rsi_sell_threshold = 55  # RSI above 65 suggests overbought (sell)


# Function to classify buy/sell signals based on RSI, we are still deciding on what we want to use as a signal

merged_data['signal'] = np.where(merged_data["macd"] > merged_data["macd_signal"], 1,0)

# def classify_signal(row):
#     if row['rsi'] < rsi_buy_threshold:
#         return 1  # Buy (Oversold)
#     elif row['rsi'] > rsi_sell_threshold:
#         return 0  # Sell (Overbought)
#     else:
#         return 2  # Hold (No strong signal)

# merged_data['signal'] = merged_data.apply(classify_signal, axis=1)

In [5]:
merged_data.isna().sum()

complete             0
volume               0
time                 0
open                 0
high                 0
low                  0
close                0
CPIAUCSL             0
GDPC1                0
UNRATE               0
DGS10                0
price_pct_change     0
price_change         0
deviation_pts        0
ema_20              19
macd                25
macd_signal         33
rsi                 13
volatility           9
hour                 0
day_of_week          0
week_of_year         0
is_weekend           0
signal               0
dtype: int64

In [6]:
scaler = StandardScaler()
merged_data['date_only'] = merged_data["time"].dt.date

unique_dates = sorted(merged_data['date_only'].unique())
total_dates = len(unique_dates)
train_end = int(total_dates * 0.7)
val_end = int(total_dates * 0.85)
train_dates = unique_dates[:train_end]
val_dates = unique_dates[train_end:val_end]
test_dates = unique_dates[val_end:]

non_numeric_cols = ['date_only', 'time', 'signal']  

train_df = merged_data[merged_data['date_only'].isin(train_dates)].copy()
val_df = merged_data[merged_data['date_only'].isin(val_dates)].copy()
test_df = merged_data[merged_data['date_only'].isin(test_dates)].copy()

X_train = train_df.drop(columns=non_numeric_cols)
X_val = val_df.drop(columns=non_numeric_cols)
X_test = test_df.drop(columns=non_numeric_cols)

X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)
X_test_scaled = scaler.transform(X_test)

y_train = train_df['signal'].reset_index(drop=True)
y_val = val_df['signal'].reset_index(drop=True)
y_test = test_df['signal'].reset_index(drop=True)

y_test.value_counts()

signal
0    67
1    29
Name: count, dtype: int64

In [7]:
from sklearn.metrics import balanced_accuracy_score, f1_score


num_hold = len(merged_data[merged_data['signal'] == 2])
num_buy = len(merged_data[merged_data['signal'] == 1])
num_sell = len(merged_data[merged_data['signal'] == 0])
scale_pos_weight_buy = num_hold / num_buy  
scale_pos_weight_sell = num_hold / num_sell 

param_grid = {
    "n_estimators": [50, 100, 200],
    "max_depth": [3, 5, 7],
    "learning_rate": [0.01, 0.1, 0.2],
    "subsample": [0.5, 0.8, 1]
}

grid_search = GridSearchCV(xgb.XGBClassifier(objective="binary:logistic"),
                           param_grid, cv=3, scoring="accuracy", verbose=2)

grid_search.fit(X_train_scaled, y_train)
#
xgb_model = xgb.XGBClassifier(**grid_search.best_params_)
xgb_model.fit(X_train_scaled, y_train,eval_set=[(X_val_scaled, y_val)], verbose=True)
y_pred = xgb_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy: {accuracy:.2f}")

Fitting 3 folds for each of 81 candidates, totalling 243 fits
[CV] END learning_rate=0.01, max_depth=3, n_estimators=50, subsample=0.5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, n_estimators=50, subsample=0.5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, n_estimators=50, subsample=0.5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, n_estimators=50, subsample=0.8; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, n_estimators=50, subsample=0.8; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, n_estimators=50, subsample=0.8; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, n_estimators=50, subsample=1; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, n_estimators=50, subsample=1; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, n_estimators=50, subsample=1; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, n_estimators=100, subsample=0.5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, n_estimators=100, subsample=0.5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, n_estimators=100, subsample=0.5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, n_estimators=100, subsample=0.8; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, n_estimators=100, subsample=0.8; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, n_estimators=100, subsample=0.8; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, n_estimators=100, subsample=1; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, n_estimators=100, subsample=1; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, n_estimators=100, subsample=1; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=3, n_estimators=200, subsample=0.5; total time=   0.1s
[CV] END learning_rate=0.01, max_depth=3, n_estimators=200, subsample=0.5; total time=   0.1s
[CV] END learning_rate=0.01, max_depth=3, n_estimators=200, subsample=0.5; total time=   0.1s
[CV] END learning_rate=0.01, max_depth=3, n_estimators=200, subsample=0.8; total time=   0.1s
[CV] END learning_rate=0.01, max_depth=3, n_estimators=200, subsample=0.8; total time=   0.1s
[CV] END learning_rate=0.01, max_depth=3, n_estimators=200, subsample=0.8; total time=   0.1s
[CV] END learning_rate=0.01, max_depth=3, n_estimators=200, subsample=1; total time=   0.1s
[CV] END learning_rate=0.01, max_depth=3, n_estimators=200, subsample=1; total time=   0.1s
[CV] END learning_rate=0.01, max_depth=3, n_estimators=200, subsample=1; total time=   0.1s
[CV] END learning_rate=0.01, max_depth=5, n_estimators=50, subsample=0.5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, n_estimators=50, subsample=0.5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, n_estimators=50, subsample=0.5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, n_estimators=50, subsample=0.8; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, n_estimators=50, subsample=0.8; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, n_estimators=50, subsample=0.8; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, n_estimators=50, subsample=1; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, n_estimators=50, subsample=1; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, n_estimators=50, subsample=1; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=5, n_estimators=100, subsample=0.5; total time=   0.1s
[CV] END learning_rate=0.01, max_depth=5, n_estimators=100, subsample=0.5; total time=   0.1s
[CV] END learning_rate=0.01, max_depth=5, n_estimators=100, subsample=0.5; total time=   0.1s
[CV] END learning_rate=0.01, max_depth=5, n_estimators=100, subsample=0.8; total time=   0.1s
[CV] END learning_rate=0.01, max_depth=5, n_estimators=100, subsample=0.8; total time=   0.1s
[CV] END learning_rate=0.01, max_depth=5, n_estimators=100, subsample=0.8; total time=   0.1s
[CV] END learning_rate=0.01, max_depth=5, n_estimators=100, subsample=1; total time=   0.1s
[CV] END learning_rate=0.01, max_depth=5, n_estimators=100, subsample=1; total time=   0.1s
[CV] END learning_rate=0.01, max_depth=5, n_estimators=100, subsample=1; total time=   0.1s
[CV] END learning_rate=0.01, max_depth=5, n_estimators=200, subsample=0.5; total time=   0.1s
[CV] END learning_rate=0.01, max_depth=5, n_estimators=200, subsample=0.5; total time=   0.1s
[CV] END learning_rate=0.01, max_depth=5, n_estimators=200, subsample=0.5; total time=   0.1s
[CV] END learning_rate=0.01, max_depth=5, n_estimators=200, subsample=0.8; total time=   0.1s
[CV] END learning_rate=0.01, max_depth=5, n_estimators=200, subsample=0.8; total time=   0.1s
[CV] END learning_rate=0.01, max_depth=5, n_estimators=200, subsample=0.8; total time=   0.1s
[CV] END learning_rate=0.01, max_depth=5, n_estimators=200, subsample=1; total time=   0.1s
[CV] END learning_rate=0.01, max_depth=5, n_estimators=200, subsample=1; total time=   0.1s
[CV] END learning_rate=0.01, max_depth=5, n_estimators=200, subsample=1; total time=   0.1s
[CV] END learning_rate=0.01, max_depth=7, n_estimators=50, subsample=0.5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, n_estimators=50, subsample=0.5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, n_estimators=50, subsample=0.5; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, n_estimators=50, subsample=0.8; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, n_estimators=50, subsample=0.8; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, n_estimators=50, subsample=0.8; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, n_estimators=50, subsample=1; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, n_estimators=50, subsample=1; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, n_estimators=50, subsample=1; total time=   0.0s
[CV] END learning_rate=0.01, max_depth=7, n_estimators=100, subsample=0.5; total time=   0.1s
[CV] END learning_rate=0.01, max_depth=7, n_estimators=100, subsample=0.5; total time=   0.1s
[CV] END learning_rate=0.01, max_depth=7, n_estimators=100, subsample=0.5; total time=   0.1s
[CV] END learning_rate=0.01, max_depth=7, n_estimators=100, subsample=0.8; total time=   0.1s
[CV] END learning_rate=0.01, max_depth=7, n_estimators=100, subsample=0.8; total time=   0.1s
[CV] END learning_rate=0.01, max_depth=7, n_estimators=100, subsample=0.8; total time=   0.1s
[CV] END learning_rate=0.01, max_depth=7, n_estimators=100, subsample=1; total time=   0.1s
[CV] END learning_rate=0.01, max_depth=7, n_estimators=100, subsample=1; total time=   0.1s
[CV] END learning_rate=0.01, max_depth=7, n_estimators=100, subsample=1; total time=   0.1s
[CV] END learning_rate=0.01, max_depth=7, n_estimators=200, subsample=0.5; total time=   0.1s
[CV] END learning_rate=0.01, max_depth=7, n_estimators=200, subsample=0.5; total time=   0.1s
[CV] END learning_rate=0.01, max_depth=7, n_estimators=200, subsample=0.5; total time=   0.1s
[CV] END learning_rate=0.01, max_depth=7, n_estimators=200, subsample=0.8; total time=   0.2s
[CV] END learning_rate=0.01, max_depth=7, n_estimators=200, subsample=0.8; total time=   0.2s
[CV] END learning_rate=0.01, max_depth=7, n_estimators=200, subsample=0.8; total time=   0.2s
[CV] END learning_rate=0.01, max_depth=7, n_estimators=200, subsample=1; total time=   0.2s
[CV] END learning_rate=0.01, max_depth=7, n_estimators=200, subsample=1; total time=   0.2s
[CV] END learning_rate=0.01, max_depth=7, n_estimators=200, subsample=1; total time=   0.2s
[CV] END learning_rate=0.1, max_depth=3, n_estimators=50, subsample=0.5; total time=   0.0s
[CV] END learning_rate=0.1, max_depth=3, n_estimators=50, subsample=0.5; total time=   0.0s
[CV] END learning_rate=0.1, max_depth=3, n_estimators=50, subsample=0.5; total time=   0.0s
[CV] END learning_rate=0.1, max_depth=3, n_estimators=50, subsample=0.8; total time=   0.0s
[CV] END learning_rate=0.1, max_depth=3, n_estimators=50, subsample=0.8; total time=   0.0s
[CV] END learning_rate=0.1, max_depth=3, n_estimators=50, subsample=0.8; total time=   0.0s
[CV] END learning_rate=0.1, max_depth=3, n_estimators=50, subsample=1; total time=   0.0s
[CV] END learning_rate=0.1, max_depth=3, n_estimators=50, subsample=1; total time=   0.0s
[CV] END learning_rate=0.1, max_depth=3, n_estimators=50, subsample=1; total time=   0.0s
[CV] END learning_rate=0.1, max_depth=3, n_estimators=100, subsample=0.5; total time=   0.0s
[CV] END learning_rate=0.1, max_depth=3, n_estimators=100, subsample=0.5; total time=   0.0s
[CV] END learning_rate=0.1, max_depth=3, n_estimators=100, subsample=0.5; total time=   0.0s
[CV] END learning_rate=0.1, max_depth=3, n_estimators=100, subsample=0.8; total time=   0.0s
[CV] END learning_rate=0.1, max_depth=3, n_estimators=100, subsample=0.8; total time=   0.0s
[CV] END learning_rate=0.1, max_depth=3, n_estimators=100, subsample=0.8; total time=   0.0s
[CV] END learning_rate=0.1, max_depth=3, n_estimators=100, subsample=1; total time=   0.0s
[CV] END learning_rate=0.1, max_depth=3, n_estimators=100, subsample=1; total time=   0.0s
[CV] END learning_rate=0.1, max_depth=3, n_estimators=100, subsample=1; total time=   0.0s
[CV] END learning_rate=0.1, max_depth=3, n_estimators=200, subsample=0.5; total time=   0.1s
[CV] END learning_rate=0.1, max_depth=3, n_estimators=200, subsample=0.5; total time=   0.1s
[CV] END learning_rate=0.1, max_depth=3, n_estimators=200, subsample=0.5; total time=   0.1s
[CV] END learning_rate=0.1, max_depth=3, n_estimators=200, subsample=0.8; total time=   0.1s
[CV] END learning_rate=0.1, max_depth=3, n_estimators=200, subsample=0.8; total time=   0.1s
[CV] END learning_rate=0.1, max_depth=3, n_estimators=200, subsample=0.8; total time=   0.1s
[CV] END learning_rate=0.1, max_depth=3, n_estimators=200, subsample=1; total time=   0.1s
[CV] END learning_rate=0.1, max_depth=3, n_estimators=200, subsample=1; total time=   0.1s
[CV] END learning_rate=0.1, max_depth=3, n_estimators=200, subsample=1; total time=   0.1s
[CV] END learning_rate=0.1, max_depth=5, n_estimators=50, subsample=0.5; total time=   0.0s
[CV] END learning_rate=0.1, max_depth=5, n_estimators=50, subsample=0.5; total time=   0.0s
[CV] END learning_rate=0.1, max_depth=5, n_estimators=50, subsample=0.5; total time=   0.0s
[CV] END learning_rate=0.1, max_depth=5, n_estimators=50, subsample=0.8; total time=   0.0s
[CV] END learning_rate=0.1, max_depth=5, n_estimators=50, subsample=0.8; total time=   0.0s
[CV] END learning_rate=0.1, max_depth=5, n_estimators=50, subsample=0.8; total time=   0.0s
[CV] END learning_rate=0.1, max_depth=5, n_estimators=50, subsample=1; total time=   0.0s
[CV] END learning_rate=0.1, max_depth=5, n_estimators=50, subsample=1; total time=   0.0s
[CV] END learning_rate=0.1, max_depth=5, n_estimators=50, subsample=1; total time=   0.0s
[CV] END learning_rate=0.1, max_depth=5, n_estimators=100, subsample=0.5; total time=   0.1s
[CV] END learning_rate=0.1, max_depth=5, n_estimators=100, subsample=0.5; total time=   0.1s
[CV] END learning_rate=0.1, max_depth=5, n_estimators=100, subsample=0.5; total time=   0.1s
[CV] END learning_rate=0.1, max_depth=5, n_estimators=100, subsample=0.8; total time=   0.1s
[CV] END learning_rate=0.1, max_depth=5, n_estimators=100, subsample=0.8; total time=   0.1s
[CV] END learning_rate=0.1, max_depth=5, n_estimators=100, subsample=0.8; total time=   0.1s
[CV] END learning_rate=0.1, max_depth=5, n_estimators=100, subsample=1; total time=   0.1s
[CV] END learning_rate=0.1, max_depth=5, n_estimators=100, subsample=1; total time=   0.1s
[CV] END learning_rate=0.1, max_depth=5, n_estimators=100, subsample=1; total time=   0.1s
[CV] END learning_rate=0.1, max_depth=5, n_estimators=200, subsample=0.5; total time=   0.1s
[CV] END learning_rate=0.1, max_depth=5, n_estimators=200, subsample=0.5; total time=   0.1s
[CV] END learning_rate=0.1, max_depth=5, n_estimators=200, subsample=0.5; total time=   0.1s
[CV] END learning_rate=0.1, max_depth=5, n_estimators=200, subsample=0.8; total time=   0.1s
[CV] END learning_rate=0.1, max_depth=5, n_estimators=200, subsample=0.8; total time=   0.1s
[CV] END learning_rate=0.1, max_depth=5, n_estimators=200, subsample=0.8; total time=   0.1s
[CV] END learning_rate=0.1, max_depth=5, n_estimators=200, subsample=1; total time=   0.1s
[CV] END learning_rate=0.1, max_depth=5, n_estimators=200, subsample=1; total time=   0.1s
[CV] END learning_rate=0.1, max_depth=5, n_estimators=200, subsample=1; total time=   0.1s
[CV] END learning_rate=0.1, max_depth=7, n_estimators=50, subsample=0.5; total time=   0.0s
[CV] END learning_rate=0.1, max_depth=7, n_estimators=50, subsample=0.5; total time=   0.0s
[CV] END learning_rate=0.1, max_depth=7, n_estimators=50, subsample=0.5; total time=   0.0s
[CV] END learning_rate=0.1, max_depth=7, n_estimators=50, subsample=0.8; total time=   0.0s
[CV] END learning_rate=0.1, max_depth=7, n_estimators=50, subsample=0.8; total time=   0.0s
[CV] END learning_rate=0.1, max_depth=7, n_estimators=50, subsample=0.8; total time=   0.0s
[CV] END learning_rate=0.1, max_depth=7, n_estimators=50, subsample=1; total time=   0.0s
[CV] END learning_rate=0.1, max_depth=7, n_estimators=50, subsample=1; total time=   0.0s
[CV] END learning_rate=0.1, max_depth=7, n_estimators=50, subsample=1; total time=   0.0s
[CV] END learning_rate=0.1, max_depth=7, n_estimators=100, subsample=0.5; total time=   0.1s
[CV] END learning_rate=0.1, max_depth=7, n_estimators=100, subsample=0.5; total time=   0.1s
[CV] END learning_rate=0.1, max_depth=7, n_estimators=100, subsample=0.5; total time=   0.1s
[CV] END learning_rate=0.1, max_depth=7, n_estimators=100, subsample=0.8; total time=   0.1s
[CV] END learning_rate=0.1, max_depth=7, n_estimators=100, subsample=0.8; total time=   0.1s
[CV] END learning_rate=0.1, max_depth=7, n_estimators=100, subsample=0.8; total time=   0.1s
[CV] END learning_rate=0.1, max_depth=7, n_estimators=100, subsample=1; total time=   0.1s
[CV] END learning_rate=0.1, max_depth=7, n_estimators=100, subsample=1; total time=   0.1s
[CV] END learning_rate=0.1, max_depth=7, n_estimators=100, subsample=1; total time=   0.1s
[CV] END learning_rate=0.1, max_depth=7, n_estimators=200, subsample=0.5; total time=   0.1s
[CV] END learning_rate=0.1, max_depth=7, n_estimators=200, subsample=0.5; total time=   0.1s
[CV] END learning_rate=0.1, max_depth=7, n_estimators=200, subsample=0.5; total time=   0.1s
[CV] END learning_rate=0.1, max_depth=7, n_estimators=200, subsample=0.8; total time=   0.1s
[CV] END learning_rate=0.1, max_depth=7, n_estimators=200, subsample=0.8; total time=   0.1s
[CV] END learning_rate=0.1, max_depth=7, n_estimators=200, subsample=0.8; total time=   0.1s
[CV] END learning_rate=0.1, max_depth=7, n_estimators=200, subsample=1; total time=   0.1s
[CV] END learning_rate=0.1, max_depth=7, n_estimators=200, subsample=1; total time=   0.1s
[CV] END learning_rate=0.1, max_depth=7, n_estimators=200, subsample=1; total time=   0.1s
[CV] END learning_rate=0.2, max_depth=3, n_estimators=50, subsample=0.5; total time=   0.0s
[CV] END learning_rate=0.2, max_depth=3, n_estimators=50, subsample=0.5; total time=   0.0s
[CV] END learning_rate=0.2, max_depth=3, n_estimators=50, subsample=0.5; total time=   0.0s
[CV] END learning_rate=0.2, max_depth=3, n_estimators=50, subsample=0.8; total time=   0.0s
[CV] END learning_rate=0.2, max_depth=3, n_estimators=50, subsample=0.8; total time=   0.0s
[CV] END learning_rate=0.2, max_depth=3, n_estimators=50, subsample=0.8; total time=   0.0s
[CV] END learning_rate=0.2, max_depth=3, n_estimators=50, subsample=1; total time=   0.0s
[CV] END learning_rate=0.2, max_depth=3, n_estimators=50, subsample=1; total time=   0.0s
[CV] END learning_rate=0.2, max_depth=3, n_estimators=50, subsample=1; total time=   0.0s
[CV] END learning_rate=0.2, max_depth=3, n_estimators=100, subsample=0.5; total time=   0.0s
[CV] END learning_rate=0.2, max_depth=3, n_estimators=100, subsample=0.5; total time=   0.0s
[CV] END learning_rate=0.2, max_depth=3, n_estimators=100, subsample=0.5; total time=   0.0s
[CV] END learning_rate=0.2, max_depth=3, n_estimators=100, subsample=0.8; total time=   0.0s
[CV] END learning_rate=0.2, max_depth=3, n_estimators=100, subsample=0.8; total time=   0.0s
[CV] END learning_rate=0.2, max_depth=3, n_estimators=100, subsample=0.8; total time=   0.0s
[CV] END learning_rate=0.2, max_depth=3, n_estimators=100, subsample=1; total time=   0.0s
[CV] END learning_rate=0.2, max_depth=3, n_estimators=100, subsample=1; total time=   0.0s
[CV] END learning_rate=0.2, max_depth=3, n_estimators=100, subsample=1; total time=   0.0s
[CV] END learning_rate=0.2, max_depth=3, n_estimators=200, subsample=0.5; total time=   0.1s
[CV] END learning_rate=0.2, max_depth=3, n_estimators=200, subsample=0.5; total time=   0.1s
[CV] END learning_rate=0.2, max_depth=3, n_estimators=200, subsample=0.5; total time=   0.1s
[CV] END learning_rate=0.2, max_depth=3, n_estimators=200, subsample=0.8; total time=   0.1s
[CV] END learning_rate=0.2, max_depth=3, n_estimators=200, subsample=0.8; total time=   0.1s
[CV] END learning_rate=0.2, max_depth=3, n_estimators=200, subsample=0.8; total time=   0.1s
[CV] END learning_rate=0.2, max_depth=3, n_estimators=200, subsample=1; total time=   0.1s
[CV] END learning_rate=0.2, max_depth=3, n_estimators=200, subsample=1; total time=   0.1s
[CV] END learning_rate=0.2, max_depth=3, n_estimators=200, subsample=1; total time=   0.1s
[CV] END learning_rate=0.2, max_depth=5, n_estimators=50, subsample=0.5; total time=   0.0s
[CV] END learning_rate=0.2, max_depth=5, n_estimators=50, subsample=0.5; total time=   0.0s
[CV] END learning_rate=0.2, max_depth=5, n_estimators=50, subsample=0.5; total time=   0.0s
[CV] END learning_rate=0.2, max_depth=5, n_estimators=50, subsample=0.8; total time=   0.0s
[CV] END learning_rate=0.2, max_depth=5, n_estimators=50, subsample=0.8; total time=   0.0s
[CV] END learning_rate=0.2, max_depth=5, n_estimators=50, subsample=0.8; total time=   0.0s
[CV] END learning_rate=0.2, max_depth=5, n_estimators=50, subsample=1; total time=   0.0s
[CV] END learning_rate=0.2, max_depth=5, n_estimators=50, subsample=1; total time=   0.0s
[CV] END learning_rate=0.2, max_depth=5, n_estimators=50, subsample=1; total time=   0.0s
[CV] END learning_rate=0.2, max_depth=5, n_estimators=100, subsample=0.5; total time=   0.0s
[CV] END learning_rate=0.2, max_depth=5, n_estimators=100, subsample=0.5; total time=   0.0s
[CV] END learning_rate=0.2, max_depth=5, n_estimators=100, subsample=0.5; total time=   0.0s
[CV] END learning_rate=0.2, max_depth=5, n_estimators=100, subsample=0.8; total time=   0.1s
[CV] END learning_rate=0.2, max_depth=5, n_estimators=100, subsample=0.8; total time=   0.0s
[CV] END learning_rate=0.2, max_depth=5, n_estimators=100, subsample=0.8; total time=   0.1s
[CV] END learning_rate=0.2, max_depth=5, n_estimators=100, subsample=1; total time=   0.0s
[CV] END learning_rate=0.2, max_depth=5, n_estimators=100, subsample=1; total time=   0.0s
[CV] END learning_rate=0.2, max_depth=5, n_estimators=100, subsample=1; total time=   0.0s
[CV] END learning_rate=0.2, max_depth=5, n_estimators=200, subsample=0.5; total time=   0.1s
[CV] END learning_rate=0.2, max_depth=5, n_estimators=200, subsample=0.5; total time=   0.1s
[CV] END learning_rate=0.2, max_depth=5, n_estimators=200, subsample=0.5; total time=   0.1s
[CV] END learning_rate=0.2, max_depth=5, n_estimators=200, subsample=0.8; total time=   0.1s
[CV] END learning_rate=0.2, max_depth=5, n_estimators=200, subsample=0.8; total time=   0.1s
[CV] END learning_rate=0.2, max_depth=5, n_estimators=200, subsample=0.8; total time=   0.1s
[CV] END learning_rate=0.2, max_depth=5, n_estimators=200, subsample=1; total time=   0.1s
[CV] END learning_rate=0.2, max_depth=5, n_estimators=200, subsample=1; total time=   0.1s

In [8]:
# do data balancement

In [9]:
print(y_val.unique())
print(y_train.unique())
print(y_test.unique())
X_val.head()

[1 0]
[0 1]
[1 0]

,complete,volume,open,high,low,close,CPIAUCSL,GDPC1,UNRATE,DGS10,...,deviation_pts,ema_20,macd,macd_signal,rsi,volatility,hour,day_of_week,week_of_year,is_weekend
380,True,1686,1.13718,1.13844,1.13714,1.13838,319.615,23542.349,4.2,4.34,...,0.105524,1.136855,0.000284,0.000100,60.560527,0.000461,0,4,16,0
381,True,8172,1.13834,1.13864,1.13628,1.13752,319.615,23542.349,4.2,4.34,...,-0.072035,1.136919,0.000299,0.000140,54.382417,0.000542,0,4,16,0
382,True,5739,1.13750,1.13778,1.13684,1.13742,319.615,23542.349,4.2,4.34,...,-0.007033,1.136966,0.000299,0.000171,53.696458,0.000523,1,4,16,0
383,True,7254,1.13743,1.13746,1.13690,1.13716,319.615,23542.349,4.2,4.34,...,-0.023738,1.136985,0.000275,0.000192,51.864695,0.000505,1,4,16,0
384,True,5294,1.13715,1.13788,1.13706,1.13732,319.615,23542.349,4.2,4.34,...,0.014950,1.137017,0.000266,0.000207,52.928862,0.000504,2,4,16,0